import { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
  {
    id: 1,
    title: "Home",
    newTab: false,
    path: "/",
  },
  {
    id: 2,
    title: "Shop",
    newTab: false,
    path: "/shop",
  },
  {
    id: 15,
    title: "VW-T5",
    newTab: false,
    path: "/vwt5",
    submenu: [
      {
        id: 100,
        title: "Exterior Styling",
        newTab: false,
        path: "/exterior-styling",
      },
      {
        id: 101,
        title: "OEM Replacement Items",
        newTab: false,
        path: "/oem-replacement-items",
      },
      {
        id: 102,
        title: "Alloy Wheels",
        newTab: false,
        path: "/alloy-wheels",
      },
      {
        id: 103,
        title: "Night Diesel Heaters",
        newTab: false,
        path: "/night-diesel-heaters",
      },
      {
        id: 104,
        title: "Kitchen Furniture Units	",
        newTab: false,
        path: "/kitchen-furniture-units",
      },
      {
        id: 105,
        title: "Upholstery",
        newTab: false,
        path: "/upholstery",
      },
      {
        id: 106,
        title: "Beds",
        newTab: false,
        path: "/beds",
      },
      {
        id: 107,
        title: "Pop Top’s",
        newTab: false,
        path: "/pop-top’s",
      },
      {
        id: 108,
        title: "Solar kits",
        newTab: false,
        path: "/solar-kits",
      },
      {
        id: 109,
        title: "Stretch carpet Kits",
        newTab: false,
        path: "/stretch-carpet-kits",
      },
      {
        id: 110,
        title: "Insulation",
        newTab: false,
        path: "/insulation",
      },
      {
        id: 111,
        title: "Flooring",
        newTab: false,
        path: "/flooring",
      },
      {
        id: 112,
        title: "Power banks",
        newTab: false,
        path: "/power-banks",
      },
      {
        id: 113,
        title: "Window Blinds",
        newTab: false,
        path: "/window-blinds",
      },
    ],
  },
  {
    id: 26,
    title: "VW-T6.1",
    newTab: false,
    path: "/vwt6.1",
    submenu: [
      {
        id: 200,
        title: "Exterior Styling",
        newTab: false,
        path: "/exterior-styling",
      },
      {
        id: 201,
        title: "OEM Replacement Items",
        newTab: false,
        path: "/oem-replacement-items",
      },
      {
        id: 202,
        title: "Alloy Wheels",
        newTab: false,
        path: "/alloy-wheels",
      },
      {
        id: 203,
        title: "Night Diesel Heaters",
        newTab: false,
        path: "/night-diesel-heaters",
      },
      {
        id: 204,
        title: "Kitchen Furniture Units	",
        newTab: false,
        path: "/kitchen-furniture-units",
      },
      {
        id: 205,
        title: "Upholstery",
        newTab: false,
        path: "/upholstery",
      },
      {
        id: 206,
        title: "Beds",
        newTab: false,
        path: "/beds",
      },
      {
        id: 207,
        title: "Pop Top’s",
        newTab: false,
        path: "/pop-top’s",
      },
      {
        id: 208,
        title: "Solar kits",
        newTab: false,
        path: "/solar-kits",
      },
      {
        id: 209,
        title: "Stretch carpet Kits",
        newTab: false,
        path: "/stretch-carpet-kits",
      },
      {
        id: 210,
        title: "Insulation",
        newTab: false,
        path: "/insulation",
      },
      {
        id: 211,
        title: "Flooring",
        newTab: false,
        path: "/flooring",
      },
      {
        id: 212,
        title: "Power banks",
        newTab: false,
        path: "/power-banks",
      },
      {
        id: 213,
        title: "Window Blinds",
        newTab: false,
        path: "/window-blinds",
      },
    ],
  },
  {
    id: 36,
    title: "VW-T7",
    newTab: false,
    path: "/vwt7",
    submenu: [
      {
        id: 300,
        title: "Exterior Styling",
        newTab: false,
        path: "/exterior-styling",
      },
      {
        id: 301,
        title: "OEM Replacement Items",
        newTab: false,
        path: "/oem-replacement-items",
      },
      {
        id: 302,
        title: "Alloy Wheels",
        newTab: false,
        path: "/alloy-wheels",
      },
      {
        id: 303,
        title: "Night Diesel Heaters",
        newTab: false,
        path: "/night-diesel-heaters",
      },
      {
        id: 304,
        title: "Kitchen Furniture Units	",
        newTab: false,
        path: "/kitchen-furniture-units",
      },
      {
        id: 305,
        title: "Upholstery",
        newTab: false,
        path: "/upholstery",
      },
      {
        id: 306,
        title: "Beds",
        newTab: false,
        path: "/beds",
      },
      {
        id: 307,
        title: "Pop Top’s",
        newTab: false,
        path: "/pop-top’s",
      },
      {
        id: 308,
        title: "Solar kits",
        newTab: false,
        path: "/solar-kits",
      },
      {
        id: 309,
        title: "Stretch carpet Kits",
        newTab: false,
        path: "/stretch-carpet-kits",
      },
      {
        id: 310,
        title: "Insulation",
        newTab: false,
        path: "/insulation",
      },
      {
        id: 311,
        title: "Flooring",
        newTab: false,
        path: "/flooring",
      },
      {
        id: 312,
        title: "Power banks",
        newTab: false,
        path: "/power-banks",
      },
      {
        id: 313,
        title: "Window Blinds",
        newTab: false,
        path: "/window-blinds",
      },
    ],
  },
  {
    id: 66,
    title: "Universal Camper Parts",
    newTab: false,
    path: "/universal-camper-parts",
    submenu: [
      {
        id: 400,
        title: "Fridge Freezer 12v 50L",
        newTab: false,
        path: "/fridge-freezer-12v-50L",
      },
      {
        id: 401,
        title: "Sink/Hob 2 burner",
        newTab: false,
        path: "/sink-hob-2-burner",
      },
      {
        id: 402,
        title: "35psi Water Pump",
        newTab: false,
        path: "/35psi-water-pump",
      },
      {
        id: 403,
        title: "Night Diesel Heaters",
        newTab: false,
        path: "/night-diesel-heaters",
      },
      {
        id: 404,
        title: "External Shower Point",
        newTab: false,
        path: "/external-shower-point",
      },
      {
        id: 405,
        title: "External Power Point",
        newTab: false,
        path: "/external-power-point",
      },
      {
        id: 406,
        title: "External Water Inlet lockable",
        newTab: false,
        path: "/external-water-inlet-lockable",
      },
    ],
  },
  {
    id: 3,
    title: "Contact",
    newTab: false,
    path: "/contact",
  },
  {
    id: 6,
    title: "pages",
    newTab: false,
    path: "/",
    submenu: [
      {
        id: 61,
        title: "Shop With Sidebar",
        newTab: false,
        path: "/shop",
      },
      {
        id: 62,
        title: "Shop Without Sidebar",
        newTab: false,
        path: "/shop-without-sidebar",
      },
      {
        id: 64,
        title: "Checkout",
        newTab: false,
        path: "/checkout",
      },
      {
        id: 65,
        title: "Cart",
        newTab: false,
        path: "/cart",
      },
      {
        id: 66,
        title: "Wishlist",
        newTab: false,
        path: "/wishlist",
      },
      {
        id: 67,
        title: "Sign in",
        newTab: false,
        path: "/signin",
      },
      {
        id: 68,
        title: "Sign up",
        newTab: false,
        path: "/signup",
      },
      {
        id: 69,
        title: "My Account",
        newTab: false,
        path: "/my-account",
      },
      {
        id: 70,
        title: "Contact",
        newTab: false,
        path: "/contact",
      },
      {
        id: 62,
        title: "Error",
        newTab: false,
        path: "/error",
      },
      {
        id: 63,
        title: "Mail Success",
        newTab: false,
        path: "/mail-success",
      },
    ],
  },
];
